// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
..............eeeeeee...........
............eeeeeeeee...........
..........eeeeeeeeeee...........
..........eeeeeeeeee............
..........eeeddddddd............
..........eeddfdddfd............
..........eeddfdddfd............
.........dd4ddddddddd...........
.........ddeddd4444dd...........
...........4dd4dddd4d...........
...........ed44d44d44...........
...........e4e4e4e4e4...........
...........4e4e4e4e4e...........
...........4ee4e4e4ee...........
............44e4e4e4............
.............eeeeeee............
..............1ddd1.............
............cc1ddd1cc...........
...........c88c1d1c8cc..........
..........cc888c1c88cc..........
..........888c881888cc..........
..........88.c881888.c..........
..........88.c888888.c..........
..........88.c888888.c..........
..........88.fffffff.c..........
..........dd.8888888.d..........
..........dd.88...88.d..........
.............88...88............
.............88...88............
.............88...88............
.............eee..eee...........
.............eee..eee...........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
