// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
..............eeeeeee...........
............eeeeeeeee...........
..........eeeeeeeeeee...........
..........eeeeeeeeee............
..........eeeddddddd............
..........eeddfdddfd............
..........eeddfdddfd............
.........dd4ddddddddd...........
.........ddeddd4444dd...........
...........4dd4dddd4d...........
...........ed44d44d44...........
...........e4e4e4e4e4...........
...........4e4e4e4e4e...........
...........4ee4e4e4ee...........
............44e4e4e4............
.............eeeeeee............
..............11111.............
............881121188...........
...........c8881218888..........
..........cc8888288888..........
..........888c88288888..........
..........88.c882888.8..........
..........88.c882888.8..........
..........88.c888888.8..........
..........88.fffffff.8..........
..........dd.8888888.d..........
..........dd.88...88.d..........
.............88...88............
.............88...88............
.............88...88............
.............eee..eee...........
.............eee..eee...........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
